using GameSrv.Script;

namespace GameSrv
{
    /// <summary>
    /// 执行指令编码定义
    /// </summary>
    public enum ExecutionCode : short
    {
        [ScriptCode("Set")]
        Set,
        [ScriptCode("Take")]
        Take,
        [ScriptCode("GIVE")]
        Give,
        [ScriptCode("TAKEW")]
        Takew,
        [ScriptCode("CLOSE")]
        Close,
        [ScriptCode("RESET")]
        ReSet,
        [ScriptCode("SETOPEN")]
        SetOpen,
        [ScriptCode("SETUNIT")]
        SetUnit,
        [ScriptCode("RESETUNIT")]
        ResetUnit,
        [ScriptCode("BREAK")]
        Break,
        [ScriptCode("TIMERECALL")]
        TimereCall,
        [ScriptCode("PARAM1")]
        Param1,
        [ScriptCode("PARAM2")]
        Param2,
        [ScriptCode("PARAM3")]
        Param3,
        [ScriptCode("PARAM4")]
        Param4,
        [ScriptCode("EXEACTION")]
        Exeaction,
        [ScriptCode("MAPMOVE")]
        MapMove,
        [ScriptCode("MAP")]
        Map,
        [ScriptCode("TAKECHECKITEM")]
        TakecheckItem,
        [ScriptCode("MONGEN")]
        MonGen,
        [ScriptCode("MONGENP")]
        MonGenp,
        [ScriptCode("MONCLEAR")]
        MonClear,
        [ScriptCode("MOV")]
        Mov,
        [ScriptCode("INC")]
        Inc,
        [ScriptCode("DEC")]
        Dec,
        [ScriptCode("SUM")]
        Sum,
        [ScriptCode("DIV")]
        Div,
        [ScriptCode("MUL")]
        Mul,
        [ScriptCode("PERCENT")]
        Percent,
        [ScriptCode("BREAKTIMERECALL")]
        BreakTimereCall,
        [ScriptCode("SENDMSG")]
        SendMsg,
        [ScriptCode("CHANGEMODE")]
        ChangeMode,
        [ScriptCode("PKPOINT")]
        PkPoint,
        [ScriptCode("CHANGEXP")]
        ChangExp,
        [ScriptCode("RECALLMOB")]
        ReCallmob,
        [ScriptCode("MOVR")]
        Movr,
        [ScriptCode("EXCHANGEMAP")]
        ExchangeMap,
        [ScriptCode("RECALLMAP")]
        ReCallMap,
        [ScriptCode("ADDBATCH")]
        Addbatch,
        [ScriptCode("BATCHDELAY")]
        Batchdelay,
        [ScriptCode("BATCHMOVE")]
        BatchMove,
        [ScriptCode("PLAYDICE")]
        Playdice,
        [ScriptCode("PASTEMAP")]
        PasteMap,
        [ScriptCode("LOADGEN")]
        LoadGen,
        [ScriptCode("ADDNAMELIST")]
        AddNameList,
        [ScriptCode("DELNAMELIST")]
        DelNameList,
        [ScriptCode("ADDGUILDLIST")]
        AddGuildList,
        [ScriptCode("DELGUILDLIST")]
        DelGuildList,
        [ScriptCode("ADDACCOUNTLIST")]
        AddAccountList,
        [ScriptCode("DELACCOUNTLIST")]
        DelAccountList,
        [ScriptCode("ADDIPLIST")]
        AddipList,
        [ScriptCode("DELIPLIST")]
        DelipList,
        [ScriptCode("GOQUEST")]
        Goquest,
        [ScriptCode("ENDQUEST")]
        Endquest,
        [ScriptCode("GOTO")]
        Goto,
        [ScriptCode("HAIRCOLOR")]
        HairColor,
        [ScriptCode("WEARCOLOR")]
        WearColor,
        [ScriptCode("HAIRSTYLE")]
        Hairstyle,
        [ScriptCode("MONRECALL")]
        MonreCall,
        [ScriptCode("HORSECALL")]
        HorseCall,
        [ScriptCode("HAIRRNDCOL")]
        Hairrndcol,
        [ScriptCode("RANDSETDAILYQUEST")]
        Randsetdailyquest,
        [ScriptCode("REFINEWEAPON")]
        RefineWeapon,
        [ScriptCode("RECALLGROUPMEMBERS")]
        ReCallgroupMembers,
        [ScriptCode("MAPTING")]
        Mapting,
        [ScriptCode("WRITEWEAPONNAME")]
        WriteWeaponName,
        [ScriptCode("ENABLECMD")]
        EnableCmd,
        [ScriptCode("LINEMSG")]
        LineMsg,
        [ScriptCode("EVENTMSG")]
        EventMsg,
        [ScriptCode("SOUNDMSG")]
        SoundMsg,
        [ScriptCode("SETMISSION")]
        SetMission,
        [ScriptCode("CLEARMISSION")]
        ClearMission,
        [ScriptCode("MONPWR")]
        Monpwr,
        [ScriptCode("ENTER_OK")]
        EnterOk,
        [ScriptCode("ENTER_FAIL")]
        EnterFail,
        [ScriptCode("MONADDITEM")]
        MonAddItem,
        [ScriptCode("CHANGEWEATHER")]
        Changeweather,
        [ScriptCode("CHANGEWEAPONATOM")]
        ChangeWeaponatom,
        [ScriptCode("GETREPAIRCOST")]
        GetrepairCost,
        [ScriptCode("KILLHORSE")]
        KillHorse,
        [ScriptCode("REPAIRITEM")]
        RepairItem,
        [ScriptCode("USEREMERGENCYCLOSE")]
        UseremerGencyClose,
        [ScriptCode("BUILDGUILD")]
        BuildGuild,
        [ScriptCode("GUILDWAR")]
        Guildwar,
        [ScriptCode("CHANGEUSERNAME")]
        ChangeUserName,
        [ScriptCode("CHANGEMONLEVEL")]
        ChangemonLevel,
        [ScriptCode("DROPITEMMAP")]
        DropItemMap,
        [ScriptCode("CLEARITEMMAP")]
        ClearItemMap,
        [ScriptCode("PROPOSECASTLEWAR")]
        Proposecastlewar,
        [ScriptCode("FINISHCASTLEWAR")]
        Finishcastlewar,
        [ScriptCode("MOVENPC")]
        MoveNpc,
        [ScriptCode("SPEAK")]
        Speak,
        [ScriptCode("SENDCMD")]
        SendCmd,
        [ScriptCode("INCFAME")]
        IncFame,
        [ScriptCode("DECFAME")]
        DecFame,
        [ScriptCode("CAPTURECASTLEFLAG")]
        CapturecastleFlag,
        [ScriptCode("MAKESHOOTER")]
        MakeShooter,
        [ScriptCode("KILLSHOOTER")]
        KillShooter,
        [ScriptCode("LEAVESHOOTER")]
        LeaveShooter,
        [ScriptCode("CHANGEMAPATTR")]
        ChangeMapAttr,
        [ScriptCode("RESETMAPATTR")]
        ResetMapAttr,
        [ScriptCode("MAKECASTLEDOOR")]
        MakeCastleDoor,
        [ScriptCode("REPAIRCASTLEDOOR")]
        RepairCastleDoor,
        [ScriptCode("CHARGESHOOTER")]
        ChargeShooter,
        [ScriptCode("SETAREAATTR")]
        SetareaAttr,
        [ScriptCode("TESTFLAG")]
        TestFlag,
        [ScriptCode("APPLYFLAG")]
        ApplyFlag,
        [ScriptCode("PASTEFLAG")]
        PasteFlag,
        [ScriptCode("GETBACKCASTLEGOLD")]
        GetBackCastleGold,
        [ScriptCode("GETBACKUPGITEM")]
        GetBackUpgItem,
        [ScriptCode("TINGWAR")]
        TingWar,
        [ScriptCode("SAVEPASSWD")]
        SavePasswd,
        [ScriptCode("CREATENPC")]
        CreateNpc,
        [ScriptCode("TAKEBONUS")]
        TakeBonus,
        [ScriptCode("SYSMSG")]
        SysMsg,
        [ScriptCode("LOADVALUE")]
        LoadValue,
        [ScriptCode("SAVEVALUE")]
        SaveValue,
        [ScriptCode("SAVELOG")]
        SaveLog,
        [ScriptCode("GETMARRIED")]
        GetMarried,
        [ScriptCode("DIVORCE")]
        Divorce,
        [ScriptCode("CAPTURESAYING")]
        CaptureSaying,
        [ScriptCode("CANCELMARRIAGERING")]
        CancelMarriagering,
        [ScriptCode("OPENUSERMARKET")]
        OpenUserMarket,
        [ScriptCode("SETTYPEUSERMARKET")]
        SettypeUserMarket,
        [ScriptCode("CHECKSOLDITEMSUSERMARKET")]
        CheckSoldItemsUserMarket,
        [ScriptCode("SETGMEMAP")]
        SetGmeMap,
        [ScriptCode("SETGMEPOINT")]
        SetGmePoint,
        [ScriptCode("SETGMETIME")]
        SetGmetTime,
        [ScriptCode("STARTNEWGME")]
        Startnewgme,
        [ScriptCode("MOVETOGMEMAP")]
        MoveToGmeMap,
        [ScriptCode("FINISHGME")]
        FinishgMe,
        [ScriptCode("CONTINUEGME")]
        Continuegme,
        [ScriptCode("SETGMEPLAYTIME")]
        SetgmeplayTime,
        [ScriptCode("SETGMEPAUSETIME")]
        SetgmepauseTime,
        [ScriptCode("SETGMELIMITUSER")]
        SetgmeLimitUser,
        [ScriptCode("SETEVENTMAP")]
        SeteventMap,
        [ScriptCode("RESETEVENTMAP")]
        ReseteventMap,
        [ScriptCode("TESTREFINEPOINTS")]
        TestrefinePoints,
        [ScriptCode("RESETREFINEWEAPON")]
        ResetrefineWeapon,
        [ScriptCode("TESTREFINEACCESSORIES")]
        Testrefineaccessories,
        [ScriptCode("REFINEACCESSORIES")]
        RefineAccessories,
        [ScriptCode("APPLYMONMISSION")]
        ApplyMonMission,
        [ScriptCode("MAPMOVER")]
        MapMover,
        [ScriptCode("ADDSTR")]
        AddStr,
        [ScriptCode("SETEVENTDAMAGE")]
        SeteventDamage,
        [ScriptCode("FORMATSTR")]
        FormatStr,
        [ScriptCode("CLEARPATH")]
        ClearPath,
        [ScriptCode("ADDPATH")]
        AddPath,
        [ScriptCode("APPLYPATH")]
        ApplyPath,
        [ScriptCode("MAPSPELL")]
        MapSpell,
        [ScriptCode("GIVEEXP")]
        GiveExp,
        [ScriptCode("GROUPMOVE")]
        GroupMove,
        [ScriptCode("GIVEEXPMAP")]
        GiveExpMap,
        [ScriptCode("APPLYMONEX")]
        ApplyMonex,
        [ScriptCode("CLEARNAMELIST")]
        ClearNameList,
        [ScriptCode("TINGCASTLEVISITOR")]
        TingCastleVisitor,
        [ScriptCode("MAKEHEALZONE")]
        MakeHealZone,
        [ScriptCode("MAKEDAMAGEZONE")]
        MakeDamageZone,
        [ScriptCode("CLEARZONE")]
        ClearZone,
        [ScriptCode("READVALUESQL")]
        ReadValueSql,
        [ScriptCode("READSTRINGSQL")]
        ReadStringSql,
        [ScriptCode("WRITEVALUESQL")]
        WriteValueSql,
        [ScriptCode("INCVALUESQL")]
        IncValueSql,
        [ScriptCode("DECVALUESQL")]
        DecValueSql,
        [ScriptCode("UPDATEVALUESQL")]
        UpDateValueSql,
        [ScriptCode("KILLSLAVE")]
        KillSlave,
        [ScriptCode("SETITEMEVENT")]
        SetItemEvent,
        [ScriptCode("REMOVEITEMEVENT")]
        ReMoveItemEvent,
        [ScriptCode("RETURN")]
        Return,
        [ScriptCode("CLEARCASTLEOWNER")]
        ClearCastleOwner,
        [ScriptCode("DISSOLUTIONGUILD")]
        DissolutionGuild,
        [ScriptCode("CHANGEGENDER")]
        ChangeGender,
        [ScriptCode("SETFAME")]
        SetFame,
        [ScriptCode("CHANGELEVEL")]
        ChangeLevel,
        [ScriptCode("MARRY")]
        Marry,
        [ScriptCode("UNMARRY")]
        UnMarry,
        [ScriptCode("GETMARRY")]
        GetMarry,
        [ScriptCode("GETMASTER")]
        GetMaster,
        [ScriptCode("CLEARSKILL")]
        ClearSkill,
        [ScriptCode("DELNOJOBSKILL")]
        DelnoJobSkill,
        [ScriptCode("DELSKILL")]
        DelSkill,
        [ScriptCode("ADDSKILL")]
        AddSkill,
        [ScriptCode("SKILLLEVEL")]
        Skilllevel,
        [ScriptCode("CHANGEPKPOINT")]
        ChangePkPoint,
        [ScriptCode("CHANGEEXP")]
        ChangeExp,
        [ScriptCode("CHANGEJOB")]
        ChangeJob,
        [ScriptCode("MISSION")]
        Mission,
        [ScriptCode("MOBPLACE")]
        Mobplace,
        [ScriptCode("SETMEMBERTYPE")]
        SetMemberType,
        [ScriptCode("SETMEMBERLEVEL")]
        SetMemberLevel,
        [ScriptCode("GAMEGOLD")]
        GameGold,
        [ScriptCode("AUTOADDGAMEGOLD")]
        AutoAddGameGold,
        [ScriptCode("AUTOSUBGAMEGOLD")]
        AutoSubGameGold,
        [ScriptCode("CHANGENAMECOLOR")]
        ChangeNameColor,
        [ScriptCode("CLEARPASSWORD")]
        ClearPassword,
        [ScriptCode("RENEWLEVEL")]
        Renewlevel,
        [ScriptCode("KILLMONEXPRATE")]
        KillMonExpRate,
        [ScriptCode("POWERRATE")]
        PowerRate,
        [ScriptCode("CHANGEPERMISSION")]
        ChangePerMission,
        [ScriptCode("KILL")]
        Kill,
        [ScriptCode("KICK")]
        Kick,
        [ScriptCode("BONUSPOINT")]
        BonusPoint,
        [ScriptCode("RESTRENEWLEVEL")]
        Restrenewlevel,
        [ScriptCode("DELMARRY")]
        DelMarry,
        [ScriptCode("DELMASTER")]
        DelMaster,
        [ScriptCode("MASTER")]
        Master,
        [ScriptCode("UNMASTER")]
        UnMaster,
        [ScriptCode("CREDITPOINT")]
        CreditPoint,
        [ScriptCode("CLEARNEEDITEMS")]
        ClearNeedItems,
        [ScriptCode("CLEARMAKEITEMS")]
        ClearMakeItems,
        [ScriptCode("SETSENDMSGFLAG")]
        SetSendMsgFlag,
        [ScriptCode("UPGRADEITEM")]
        UpgradeItems,
        [ScriptCode("UPGRADEITEMEX")]
        UpgradeItemsex,
        [ScriptCode("MONGENEX")]
        MonGenex,
        [ScriptCode("CLEARMAPMON")]
        ClearMapMon,
        [ScriptCode("SETMPAMODE")]
        SetMapMode,
        [ScriptCode("GAMEPOINT")]
        GamePoint,
        [ScriptCode("PKZONE")]
        PvpZone,
        [ScriptCode("RESTBONUSPOINT")]
        RestBonusPoint,
        [ScriptCode("TAKECASTLEGOLD")]
        TakeCastleGold,
        [ScriptCode("HUMANHP")]
        HumanHp,
        [ScriptCode("HUMANMP")]
        HumanMp,
        [ScriptCode("GUILDBUILDPOINT")]
        BuildPoint,
        [ScriptCode("GUILDAURAEPOINT")]
        AuraePoint,
        [ScriptCode("GUILDSTABILITYPOINT")]
        StabilityPoint,
        [ScriptCode("GUILDFLOURISHPOINT")]
        FlourishPoint,
        [ScriptCode("OPENITEMBOX")]
        OpenMagicbox,
        [ScriptCode("SETRANKLEVELNAME")]
        SetRankLevelName,
        [ScriptCode("GMEXECUTE")]
        GmExecute,
        [ScriptCode("GUILDCHIEFITEMCOUNT")]
        GuildChiefItemCount,
        [ScriptCode("ADDNAMEDATELIST")]
        AddNameDateList,
        [ScriptCode("DELNAMEDATELIST")]
        DelNameDateList,
        [ScriptCode("MOBFIREBURN")]
        MobFireburn,
        [ScriptCode("MESSAGEBOX")]
        MessageBox,
        [ScriptCode("SETSCRIPTFLAG")]
        SetscriptFlag,
        [ScriptCode("SETAUTOGETEXP")]
        SetautogetExp,
        [ScriptCode("VAR")]
        Var,
        [ScriptCode("LOADVAR")]
        LoadVar,
        [ScriptCode("SAVEVAR")]
        SaveVar,
        [ScriptCode("CALCVAR")]
        CalcVar,
        [ScriptCode("OFFLINEPLAY")]
        OffLinePlay,
        [ScriptCode("KICKOFFLINE")]
        KickOffline,
        [ScriptCode("STARTTAKEGOLD")]
        StarttakeGold,
        [ScriptCode("CLEARDELAYGOTO")]
        ClearDelayGoto,
        [ScriptCode("CHANGERECOMMENDGAMEGOLD")]
        ChangereCommendGameGold,
        [ScriptCode("ANSIREPLACETEXT")]
        AnsirePlaceText,
        [ScriptCode("ENCODETEXT")]
        EncodeText,
        [ScriptCode("DECODETEXT")]
        DecodeText,
        [ScriptCode("ADDTEXTLIST")]
        AddTextList,
        [ScriptCode("DELTEXTLIST")]
        DelTextList,
        [ScriptCode("GROUPMAPMOVE")]
        GroupMapMove,
        [ScriptCode("RECALLHUMAN")]
        ReCallHuman,
        [ScriptCode("REGOTO")]
        Regoto,
        [ScriptCode("INTTOSTR")]
        IntToStr,
        [ScriptCode("STRTOINT")]
        StrToInt,
        [ScriptCode("GUILDMOVE")]
        GuildMove,
        [ScriptCode("GUILDMAPMOVE")]
        GuildMapMove,
        [ScriptCode("RANDOMMOVE")]
        RandomMove,
        [ScriptCode("USEBONUSPOINT")]
        UseBonusPoint,
        [ScriptCode("TAKEONITEM")]
        TakeOnItem,
        [ScriptCode("TAKEOFFITEM")]
        TakeOffItem,
        [ScriptCode("GIVEEX")]
        GiveEx,
        [ScriptCode("TIMEOPEN")]
        TimeOpen,
        [ScriptCode("TIMECLOSE")]
        TimeClose,
        [ScriptCode("GUILDMEMBERMAXLIMIT")]
        GuildMemberMaxLimit,
        [ScriptCode("ADDGUILDNAMEDATELIST")]
        AddGuildNamedateList,
        [ScriptCode("DELGUILDNAMEDATELIST")]
        DelGuildNamedateList,
        [ScriptCode("GOHOME")]
        GoHome,
        [ScriptCode("ADDBLOCKIPLIST")]
        AddBlockIpList,
        [ScriptCode("MOVEDATA")]
        MovData,
        [ScriptCode("SENDCOLORMSG")]
        SendColorMsg,
        [ScriptCode("ADDRANDOMMAPGATE")]
        AddRandomMapGate,
        [ScriptCode("DELRANDOMMAPGATE")]
        DelRandomMapGate,
        [ScriptCode("GETRANDOMMAPGATE")]
        GetRandommApGate,
        [ScriptCode("OPENBOOK")]
        OpenBook,
        [ScriptCode("OPENBOX")]
        OpenBox,
        [ScriptCode("CHANGEITEMS")]
        ChangeItems,
        [ScriptCode("CLEARREMEMBER")]
        ClearreMember,
        [ScriptCode("SENDMOVEMSG")]
        SendMoveMsg,
        [ScriptCode("SETITEMSLIGHT")]
        SetItemsLight,
        [ScriptCode("READRANDOMSTR")]
        ReadrandomStr,
        [ScriptCode("CHANGERANGEMONPOS")]
        ChangeRangeMonPos,
        [ScriptCode("READ")]
        Read,
        [ScriptCode("WRITE")]
        Write,
        [ScriptCode("CHANGEITEMNEWADDVALUE")]
        ChangeItemNewAddValue,
        [ScriptCode("OPENHOMEPAGE")]
        OpenHomePage,
        [ScriptCode("PKZONEX")]
        PvpZoneEx,
        [ScriptCode("SETITEMSLIGHTEX")]
        SetItemslightex,
        [ScriptCode("SPELL")]
        Spell,
        [ScriptCode("ADDMAPMAGICEVENT")]
        AddMapMagicEvent,
        [ScriptCode("RANDOMADDMAPMAGICEVENT")]
        RandomAddMapMagicEvent,
        [ScriptCode("SNOW")]
        SNow,
        [ScriptCode("RANDOMUPGRADEITEM")]
        RandoMupgradeItem,
        [ScriptCode("LOCK")]
        Lock,
        [ScriptCode("UNLOCK")]
        Unlock,
        [ScriptCode("GETDUELITEMS")]
        GetdUelItems,
        [ScriptCode("CANUSEITEM")]
        CanUseItem,
        [ScriptCode("AUTOGOTOXY")]
        AutoGotoxy,
        [ScriptCode("CHANGENEWSTATUS")]
        ChangeNewStatus,
        [ScriptCode("SENDDELAYMSG")]
        SendDelayMsg,
        [ScriptCode("ACTVARLIST")]
        ActvarList,
        [ScriptCode("SETMASKED")]
        SetMasked,
        [ScriptCode("SENDCENTERMSG")]
        SendCenterMsg,
        [ScriptCode("CHANGEUSEITEMSTARSLEVEL")]
        ChangeUseItemStarsLevel,
        [ScriptCode("CHANGEBAGITEMSTARSLEVEL")]
        ChangeBagItemStarsLevel,
        [ScriptCode("BINDBAGITEM")]
        BindbagItem,
        [ScriptCode("SETONTIMER")]
        SetOnTimer,
        [ScriptCode("SETOFFTIMER")]
        KillScTimer,
        [ScriptCode("PLAYSOUND")]
        PlaySound,
        [ScriptCode("SHOWEFFECT")]
        ShowEffect,
        [ScriptCode("CHANGEITEMVALUE")]
        ChangeItemvalue,
        [ScriptCode("VIBRATION")]
        Vibration,
        [ScriptCode("OPENBIGDIALOGBOX")]
        OpenbigDialogBox,
        [ScriptCode("CLOSEBIGDIALOGBOX")]
        CloseBigDialogBox,
        [ScriptCode("TAGMAPMOVE")]
        TagMapMove,
        [ScriptCode("TAGMAPINFO")]
        TagMapinfo,
        [ScriptCode("AISTART")]
        AiStart,
        [ScriptCode("AISTOP")]
        AiStop,
        [ScriptCode("CHANGEIPADDRESS")]
        ChangeIpAddress,
        [ScriptCode("CHANGEATTATCKMODE")]
        ChangeAttatckMode,
        [ScriptCode("AILOGON")]
        AiLogon,
        [ScriptCode("AILOGONEX")]
        AiLogonEx,
        [ScriptCode("KICKALL")]
        KickAll,
        [ScriptCode("TAKEITEMLIST")]
        TakeItemList,
        [ScriptCode("SHOWRANKLEVLNAME")]
        ShowRankLevlName,
        [ScriptCode("LOADROBOTCONFIG")]
        LoadRobotConfig,
        [ScriptCode("ACTMISSION")]
        ActMission,
        [ScriptCode("GUILDRECALL")]
        GuildReCall,
        [ScriptCode("GROUPADDLIST")]
        GroupAddList,
        [ScriptCode("CLEARLIST")]
        ClearList,
        [ScriptCode("GROUPRECALL")]
        GroupReCall,
        [ScriptCode("GROUPMOVEMAP")]
        GroupMoveMap,
        [ScriptCode("SAVESLAVES")]
        SaveSlaves,
        /// <summary>
        // 检查会员时间
        /// </summary>
        [ScriptCode("CHECKUSERDATE")]
        CheckUserDate,
        /// <summary>
        /// 加入会员人物及时间
        /// </summary>
        [ScriptCode("ADDUSERDATE")]
        AddUserDate,
        /// <summary>
        /// 删除会员人物及时间
        /// </summary>
        [ScriptCode("DELUSERDATE")]
        DelUserDate,
        /// <summary>
        /// 挂机
        /// </summary>
        [ScriptCode("OFFLINE")]
        OffLine,
        /// <summary>
        /// 特修身上所有装备
        /// </summary>
        [ScriptCode("REPAIRALL")]
        RepairAll,
        /// <summary>
        /// 产生一个随机数字
        /// </summary>
        [ScriptCode("SETRANDOMNO")]
        SetRandomNo,
        /// <summary>
        /// 刷新包裹物品命令
        /// </summary>
        [ScriptCode("QUERYBAGITEMS")]
        QueryBagItems,
        /// <summary>
        /// 将指定物品刷新到指定地图坐标范围内
        /// </summary>
        [ScriptCode("THROWITEM")]
        ThrowItem,
        /// <summary>
        /// 开通元宝交易
        /// </summary>
        [ScriptCode("OPENYBDEAL")]
        OpenYbDeal,
        /// <summary>
        /// 查询可以购买的物品
        /// </summary>        
        [ScriptCode("QUERYYBSELL")]
        QueryYbSell,
        /// <summary>
        /// 查询元宝交易
        /// </summary>
        [ScriptCode("QUERYYBDEAL")]
        QueryYbDeal,
        /// <summary>
        /// 延时跳转
        /// </summary>
        [ScriptCode("DELAYGOTO")]
        DelayGoto,
        /// <summary>
        /// 延时跳转
        /// </summary>
        [ScriptCode("DELAYCALL")]
        DelayCall,
        /// <summary>
        /// 获取客户端输入值
        /// </summary>
        [ScriptCode("QUERYVALUE")]
        QueryValue,
        /// <summary>
        /// 杀死所有宠物
        /// </summary>
        [ScriptCode("KILLSLAVENAME")]
        KillSlaveName,
        /// <summary>
        /// 查询物品信息
        /// </summary>
        [ScriptCode("QUERYITEMDLG")]
        QueryItemDlg,
        /// <summary>
        /// 升级对话框中的物品
        /// </summary>
        [ScriptCode("UPGRADEDLGITEM")]
        UpgradeDlgItem,
        /// <summary>
        /// 获取装备指定属性到变量中
        /// </summary>
        [ScriptCode("GETDLGITEMVALUE")]
        GetDlgItemValue,
        /// <summary>
        /// 回收对话框中的物品
        /// </summary>
        [ScriptCode("TAKEDLGITEM")]
        TakeDlgItem
    }
}