using GameSrv.Script;

namespace GameSrv
{
    /// <summary>
    /// 执行指令编码定义
    /// </summary>
    public enum ExecutionCode : short
    {
        [ScriptCode("Set")]
        SET,
        [ScriptCode("Take")]
        TAKE,
        [ScriptCode("GIVE")]
        GIVE,
        [ScriptCode("TAKEW")]
        TAKEW,
        [ScriptCode("CLOSE")]
        CLOSE,
        [ScriptCode("RESET")]
        RESET,
        [ScriptCode("SETOPEN")]
        SETOPEN,
        [ScriptCode("SETUNIT")]
        SETUNIT,
        [ScriptCode("RESETUNIT")]
        RESETUNIT,
        [ScriptCode("BREAK")]
        BREAK,
        [ScriptCode("TIMERECALL")]
        TIMERECALL,
        [ScriptCode("PARAM1")]
        PARAM1,
        [ScriptCode("PARAM2")]
        PARAM2,
        [ScriptCode("PARAM3")]
        PARAM3,
        [ScriptCode("PARAM4")]
        PARAM4,
        [ScriptCode("EXEACTION")]
        EXEACTION,
        [ScriptCode("MAPMOVE")]
        MAPMOVE,
        [ScriptCode("MAP")]
        MAP,
        [ScriptCode("TAKECHECKITEM")]
        TAKECHECKITEM,
        [ScriptCode("MONGEN")]
        MONGEN,
        [ScriptCode("MONGENP")]
        MONGENP,
        [ScriptCode("MONCLEAR")]
        MONCLEAR,
        [ScriptCode("MOV")]
        MOV,
        [ScriptCode("INC")]
        INC,
        [ScriptCode("DEC")]
        DEC,
        [ScriptCode("SUM")]
        SUM,
        [ScriptCode("DIV")]
        Div,
        [ScriptCode("MUL")]
        Mul,
        [ScriptCode("PERCENT")]
        Percent,
        [ScriptCode("BREAKTIMERECALL")]
        BREAKTIMERECALL,
        [ScriptCode("SENDMSG")]
        SENDMSG,
        [ScriptCode("CHANGEMODE")]
        CHANGEMODE,
        [ScriptCode("PKPOINT")]
        PKPOINT,
        [ScriptCode("CHANGEXP")]
        CHANGEXP,
        [ScriptCode("RECALLMOB")]
        RECALLMOB,
        [ScriptCode("MOVR")]
        MOVR,
        [ScriptCode("EXCHANGEMAP")]
        EXCHANGEMAP,
        [ScriptCode("RECALLMAP")]
        RECALLMAP,
        [ScriptCode("ADDBATCH")]
        ADDBATCH,
        [ScriptCode("BATCHDELAY")]
        BATCHDELAY,
        [ScriptCode("BATCHMOVE")]
        BATCHMOVE,
        [ScriptCode("PLAYDICE")]
        PLAYDICE,
        [ScriptCode("PASTEMAP")]
        PASTEMAP,
        [ScriptCode("LOADGEN")]
        LOADGEN,
        [ScriptCode("ADDNAMELIST")]
        ADDNAMELIST,
        [ScriptCode("DELNAMELIST")]
        DELNAMELIST,
        [ScriptCode("ADDGUILDLIST")]
        ADDGUILDLIST,
        [ScriptCode("DELGUILDLIST")]
        DELGUILDLIST,
        [ScriptCode("ADDACCOUNTLIST")]
        ADDACCOUNTLIST,
        [ScriptCode("DELACCOUNTLIST")]
        DELACCOUNTLIST,
        [ScriptCode("ADDIPLIST")]
        ADDIPLIST,
        [ScriptCode("DELIPLIST")]
        DELIPLIST,
        [ScriptCode("GOQUEST")]
        GOQUEST,
        [ScriptCode("ENDQUEST")]
        ENDQUEST,
        [ScriptCode("GOTO")]
        GOTO,
        [ScriptCode("HAIRCOLOR")]
        HAIRCOLOR,
        [ScriptCode("WEARCOLOR")]
        WEARCOLOR,
        [ScriptCode("HAIRSTYLE")]
        HAIRSTYLE,
        [ScriptCode("MONRECALL")]
        MONRECALL,
        [ScriptCode("HORSECALL")]
        HORSECALL,
        [ScriptCode("HAIRRNDCOL")]
        HAIRRNDCOL,
        [ScriptCode("RANDSETDAILYQUEST")]
        RANDSETDAILYQUEST,
        [ScriptCode("REFINEWEAPON")]
        REFINEWEAPON,
        [ScriptCode("RECALLGROUPMEMBERS")]
        RECALLGROUPMEMBERS,
        [ScriptCode("MAPTING")]
        MAPTING,
        [ScriptCode("WRITEWEAPONNAME")]
        WRITEWEAPONNAME,
        [ScriptCode("ENABLECMD")]
        ENABLECMD,
        [ScriptCode("LINEMSG")]
        LINEMSG,
        [ScriptCode("EVENTMSG")]
        EVENTMSG,
        [ScriptCode("SOUNDMSG")]
        SOUNDMSG,
        [ScriptCode("SETMISSION")]
        SETMISSION,
        [ScriptCode("CLEARMISSION")]
        CLEARMISSION,
        [ScriptCode("MONPWR")]
        MONPWR,
        [ScriptCode("ENTER_OK")]
        ENTER_OK,
        [ScriptCode("ENTER_FAIL")]
        ENTER_FAIL,
        [ScriptCode("MONADDITEM")]
        MONADDITEM,
        [ScriptCode("CHANGEWEATHER")]
        CHANGEWEATHER,
        [ScriptCode("CHANGEWEAPONATOM")]
        CHANGEWEAPONATOM,
        [ScriptCode("GETREPAIRCOST")]
        GETREPAIRCOST,
        [ScriptCode("KILLHORSE")]
        KILLHORSE,
        [ScriptCode("REPAIRITEM")]
        REPAIRITEM,
        [ScriptCode("USEREMERGENCYCLOSE")]
        USEREMERGENCYCLOSE,
        [ScriptCode("BUILDGUILD")]
        BUILDGUILD,
        [ScriptCode("GUILDWAR")]
        GUILDWAR,
        [ScriptCode("CHANGEUSERNAME")]
        CHANGEUSERNAME,
        [ScriptCode("CHANGEMONLEVEL")]
        CHANGEMONLEVEL,
        [ScriptCode("DROPITEMMAP")]
        DROPITEMMAP,
        [ScriptCode("CLEARITEMMAP")]
        CLEARITEMMAP,
        [ScriptCode("PROPOSECASTLEWAR")]
        PROPOSECASTLEWAR,
        [ScriptCode("FINISHCASTLEWAR")]
        FINISHCASTLEWAR,
        [ScriptCode("MOVENPC")]
        MOVENPC,
        [ScriptCode("SPEAK")]
        SPEAK,
        [ScriptCode("SENDCMD")]
        SENDCMD,
        [ScriptCode("INCFAME")]
        INCFAME,
        [ScriptCode("DECFAME")]
        DECFAME,
        [ScriptCode("CAPTURECASTLEFLAG")]
        CAPTURECASTLEFLAG,
        [ScriptCode("MAKESHOOTER")]
        MAKESHOOTER,
        [ScriptCode("KILLSHOOTER")]
        KILLSHOOTER,
        [ScriptCode("LEAVESHOOTER")]
        LEAVESHOOTER,
        [ScriptCode("CHANGEMAPATTR")]
        CHANGEMAPATTR,
        [ScriptCode("RESETMAPATTR")]
        RESETMAPATTR,
        [ScriptCode("MAKECASTLEDOOR")]
        MAKECASTLEDOOR,
        [ScriptCode("REPAIRCASTLEDOOR")]
        REPAIRCASTLEDOOR,
        [ScriptCode("CHARGESHOOTER")]
        CHARGESHOOTER,
        [ScriptCode("SETAREAATTR")]
        SETAREAATTR,
        [ScriptCode("TESTFLAG")]
        TESTFLAG,
        [ScriptCode("APPLYFLAG")]
        APPLYFLAG,
        [ScriptCode("PASTEFLAG")]
        PASTEFLAG,
        [ScriptCode("GETBACKCASTLEGOLD")]
        GETBACKCASTLEGOLD,
        [ScriptCode("GETBACKUPGITEM")]
        GETBACKUPGITEM,
        [ScriptCode("TINGWAR")]
        TINGWAR,
        [ScriptCode("SAVEPASSWD")]
        SAVEPASSWD,
        [ScriptCode("CREATENPC")]
        CREATENPC,
        [ScriptCode("TAKEBONUS")]
        TAKEBONUS,
        [ScriptCode("SYSMSG")]
        SYSMSG,
        [ScriptCode("LOADVALUE")]
        LOADVALUE,
        [ScriptCode("SAVEVALUE")]
        SAVEVALUE,
        [ScriptCode("SAVELOG")]
        SAVELOG,
        [ScriptCode("GETMARRIED")]
        GETMARRIED,
        [ScriptCode("DIVORCE")]
        DIVORCE,
        [ScriptCode("CAPTURESAYING")]
        CAPTURESAYING,
        [ScriptCode("CANCELMARRIAGERING")]
        CANCELMARRIAGERING,
        [ScriptCode("OPENUSERMARKET")]
        OPENUSERMARKET,
        [ScriptCode("SETTYPEUSERMARKET")]
        SETTYPEUSERMARKET,
        [ScriptCode("CHECKSOLDITEMSUSERMARKET")]
        CHECKSOLDITEMSUSERMARKET,
        [ScriptCode("SETGMEMAP")]
        SETGMEMAP,
        [ScriptCode("SETGMEPOINT")]
        SETGMEPOINT,
        [ScriptCode("SETGMETIME")]
        SETGMETIME,
        [ScriptCode("STARTNEWGME")]
        STARTNEWGME,
        [ScriptCode("MOVETOGMEMAP")]
        MOVETOGMEMAP,
        [ScriptCode("FINISHGME")]
        FINISHGME,
        [ScriptCode("CONTINUEGME")]
        CONTINUEGME,
        [ScriptCode("SETGMEPLAYTIME")]
        SETGMEPLAYTIME,
        [ScriptCode("SETGMEPAUSETIME")]
        SETGMEPAUSETIME,
        [ScriptCode("SETGMELIMITUSER")]
        SETGMELIMITUSER,
        [ScriptCode("SETEVENTMAP")]
        SETEVENTMAP,
        [ScriptCode("RESETEVENTMAP")]
        RESETEVENTMAP,
        [ScriptCode("TESTREFINEPOINTS")]
        TESTREFINEPOINTS,
        [ScriptCode("RESETREFINEWEAPON")]
        RESETREFINEWEAPON,
        [ScriptCode("TESTREFINEACCESSORIES")]
        TESTREFINEACCESSORIES,
        [ScriptCode("REFINEACCESSORIES")]
        REFINEACCESSORIES,
        [ScriptCode("APPLYMONMISSION")]
        APPLYMONMISSION,
        [ScriptCode("MAPMOVER")]
        MAPMOVER,
        [ScriptCode("ADDSTR")]
        ADDSTR,
        [ScriptCode("SETEVENTDAMAGE")]
        SETEVENTDAMAGE,
        [ScriptCode("FORMATSTR")]
        FORMATSTR,
        [ScriptCode("CLEARPATH")]
        CLEARPATH,
        [ScriptCode("ADDPATH")]
        ADDPATH,
        [ScriptCode("APPLYPATH")]
        APPLYPATH,
        [ScriptCode("MAPSPELL")]
        MAPSPELL,
        [ScriptCode("GIVEEXP")]
        GIVEEXP,
        [ScriptCode("GROUPMOVE")]
        GROUPMOVE,
        [ScriptCode("GIVEEXPMAP")]
        GIVEEXPMAP,
        [ScriptCode("APPLYMONEX")]
        APPLYMONEX,
        [ScriptCode("CLEARNAMELIST")]
        CLEARNAMELIST,
        [ScriptCode("TINGCASTLEVISITOR")]
        TINGCASTLEVISITOR,
        [ScriptCode("MAKEHEALZONE")]
        MAKEHEALZONE,
        [ScriptCode("MAKEDAMAGEZONE")]
        MAKEDAMAGEZONE,
        [ScriptCode("CLEARZONE")]
        CLEARZONE,
        [ScriptCode("READVALUESQL")]
        READVALUESQL,
        [ScriptCode("READSTRINGSQL")]
        READSTRINGSQL,
        [ScriptCode("WRITEVALUESQL")]
        WRITEVALUESQL,
        [ScriptCode("INCVALUESQL")]
        INCVALUESQL,
        [ScriptCode("DECVALUESQL")]
        DECVALUESQL,
        [ScriptCode("UPDATEVALUESQL")]
        UPDATEVALUESQL,
        [ScriptCode("KILLSLAVE")]
        KILLSLAVE,
        [ScriptCode("SETITEMEVENT")]
        SETITEMEVENT,
        [ScriptCode("REMOVEITEMEVENT")]
        REMOVEITEMEVENT,
        [ScriptCode("RETURN")]
        RETURN,
        [ScriptCode("CLEARCASTLEOWNER")]
        CLEARCASTLEOWNER,
        [ScriptCode("DISSOLUTIONGUILD")]
        DISSOLUTIONGUILD,
        [ScriptCode("CHANGEGENDER")]
        CHANGEGENDER,
        [ScriptCode("SETFAME")]
        SETFAME,
        [ScriptCode("CHANGELEVEL")]
        CHANGELEVEL,
        [ScriptCode("MARRY")]
        MARRY,
        [ScriptCode("UNMARRY")]
        UNMARRY,
        [ScriptCode("GETMARRY")]
        GETMARRY,
        [ScriptCode("GETMASTER")]
        GETMASTER,
        [ScriptCode("CLEARSKILL")]
        CLEARSKILL,
        [ScriptCode("DELNOJOBSKILL")]
        DELNOJOBSKILL,
        [ScriptCode("DELSKILL")]
        DELSKILL,
        [ScriptCode("ADDSKILL")]
        ADDSKILL,
        [ScriptCode("SKILLLEVEL")]
        SKILLLEVEL,
        [ScriptCode("CHANGEPKPOINT")]
        CHANGEPKPOINT,
        [ScriptCode("CHANGEEXP")]
        CHANGEEXP,
        [ScriptCode("CHANGEJOB")]
        CHANGEJOB,
        [ScriptCode("MISSION")]
        MISSION,
        [ScriptCode("MOBPLACE")]
        MOBPLACE,
        [ScriptCode("SETMEMBERTYPE")]
        SETMEMBERTYPE,
        [ScriptCode("SETMEMBERLEVEL")]
        SETMEMBERLEVEL,
        [ScriptCode("GAMEGOLD")]
        GAMEGOLD,
        [ScriptCode("AUTOADDGAMEGOLD")]
        AUTOADDGAMEGOLD,
        [ScriptCode("AUTOSUBGAMEGOLD")]
        AUTOSUBGAMEGOLD,
        [ScriptCode("CHANGENAMECOLOR")]
        CHANGENAMECOLOR,
        [ScriptCode("CLEARPASSWORD")]
        CLEARPASSWORD,
        [ScriptCode("RENEWLEVEL")]
        RENEWLEVEL,
        [ScriptCode("KILLMONEXPRATE")]
        KILLMONEXPRATE,
        [ScriptCode("POWERRATE")]
        POWERRATE,
        [ScriptCode("CHANGEPERMISSION")]
        CHANGEPERMISSION,
        [ScriptCode("KILL")]
        KILL,
        [ScriptCode("KICK")]
        KICK,
        [ScriptCode("BONUSPOINT")]
        BONUSPOINT,
        [ScriptCode("RESTRENEWLEVEL")]
        RESTRENEWLEVEL,
        [ScriptCode("DELMARRY")]
        DELMARRY,
        [ScriptCode("DELMASTER")]
        DELMASTER,
        [ScriptCode("MASTER")]
        MASTER,
        [ScriptCode("UNMASTER")]
        UNMASTER,
        [ScriptCode("CREDITPOINT")]
        CREDITPOINT,
        [ScriptCode("CLEARNEEDITEMS")]
        CLEARNEEDITEMS,
        [ScriptCode("CLEARMAKEITEMS")]
        CLEARMAKEITEMS,
        [ScriptCode("SETSENDMSGFLAG")]
        SETSENDMSGFLAG,
        [ScriptCode("UPGRADEITEM")]
        UPGRADEITEMS,
        [ScriptCode("UPGRADEITEMEX")]
        UPGRADEITEMSEX,
        [ScriptCode("MONGENEX")]
        MONGENEX,
        [ScriptCode("CLEARMAPMON")]
        CLEARMAPMON,
        [ScriptCode("SETMPAMODE")]
        SETMAPMODE,
        [ScriptCode("GAMEPOINT")]
        GAMEPOINT,
        [ScriptCode("PKZONE")]
        PKZONE,
        [ScriptCode("RESTBONUSPOINT")]
        RESTBONUSPOINT,
        [ScriptCode("TAKECASTLEGOLD")]
        TAKECASTLEGOLD,
        [ScriptCode("HUMANHP")]
        HUMANHP,
        [ScriptCode("HUMANMP")]
        HUMANMP,
        [ScriptCode("GUILDBUILDPOINT")]
        BUILDPOINT,
        [ScriptCode("GUILDAURAEPOINT")]
        AURAEPOINT,
        [ScriptCode("GUILDSTABILITYPOINT")]
        STABILITYPOINT,
        [ScriptCode("GUILDFLOURISHPOINT")]
        FLOURISHPOINT,
        [ScriptCode("OPENITEMBOX")]
        OPENMAGICBOX,
        [ScriptCode("SETRANKLEVELNAME")]
        SETRANKLEVELNAME,
        [ScriptCode("GMEXECUTE")]
        GMEXECUTE,
        [ScriptCode("GUILDCHIEFITEMCOUNT")]
        GUILDCHIEFITEMCOUNT,
        [ScriptCode("ADDNAMEDATELIST")]
        ADDNAMEDATELIST,
        [ScriptCode("DELNAMEDATELIST")]
        DELNAMEDATELIST,
        [ScriptCode("MOBFIREBURN")]
        MOBFIREBURN,
        [ScriptCode("MESSAGEBOX")]
        MESSAGEBOX,
        [ScriptCode("SETSCRIPTFLAG")]
        SETSCRIPTFLAG,
        [ScriptCode("SETAUTOGETEXP")]
        SETAUTOGETEXP,
        [ScriptCode("VAR")]
        VAR,
        [ScriptCode("LOADVAR")]
        LOADVAR,
        [ScriptCode("SAVEVAR")]
        SAVEVAR,
        [ScriptCode("CALCVAR")]
        CALCVAR,
        [ScriptCode("OFFLINEPLAY")]
        nOFFLINEPLAY,
        [ScriptCode("KICKOFFLINE")]
        nKICKOFFLINE,
        [ScriptCode("STARTTAKEGOLD")]
        nSTARTTAKEGOLD,
        [ScriptCode("CLEARDELAYGOTO")]
        CLEARDELAYGOTO,
        [ScriptCode("CHANGERECOMMENDGAMEGOLD")]
        nCHANGERECOMMENDGAMEGOLD,
        [ScriptCode("ANSIREPLACETEXT")]
        ANSIREPLACETEXT,
        [ScriptCode("ENCODETEXT")]
        ENCODETEXT,
        [ScriptCode("DECODETEXT")]
        DECODETEXT,
        [ScriptCode("ADDTEXTLIST")]
        ADDTEXTLIST,
        [ScriptCode("DELTEXTLIST")]
        DELTEXTLIST,
        [ScriptCode("GROUPMAPMOVE")]
        GROUPMAPMOVE,
        [ScriptCode("RECALLHUMAN")]
        RECALLHUMAN,
        [ScriptCode("REGOTO")]
        REGOTO,
        [ScriptCode("INTTOSTR")]
        INTTOSTR,
        [ScriptCode("STRTOINT")]
        STRTOINT,
        [ScriptCode("GUILDMOVE")]
        GUILDMOVE,
        [ScriptCode("GUILDMAPMOVE")]
        GUILDMAPMOVE,
        [ScriptCode("RANDOMMOVE")]
        RANDOMMOVE,
        [ScriptCode("USEBONUSPOINT")]
        USEBONUSPOINT,
        [ScriptCode("TAKEONITEM")]
        TAKEONITEM,
        [ScriptCode("TAKEOFFITEM")]
        TAKEOFFITEM,
        [ScriptCode("CREATEHERO")]
        CREATEHERO,
        [ScriptCode("DELETEHERO")]
        DELETEHERO,
        [ScriptCode("GIVEEX")]
        GIVEEX,
        [ScriptCode("TIMEOPEN")]
        TIMEOPEN,
        [ScriptCode("TIMECLOSE")]
        TIMECLOSE,
        [ScriptCode("GUILDMEMBERMAXLIMIT")]
        GUILDMEMBERMAXLIMIT,
        [ScriptCode("ADDGUILDNAMEDATELIST")]
        ADDGUILDNAMEDATELIST,
        [ScriptCode("DELGUILDNAMEDATELIST")]
        DELGUILDNAMEDATELIST,
        [ScriptCode("GOHOME")]
        GOHOME,
        [ScriptCode("ADDBLOCKIPLIST")]
        ADDBLOCKIPLIST,
        [ScriptCode("MOVEDATA")]
        MOVDATA,
        [ScriptCode("SENDCOLORMSG")]
        SENDCOLORMSG,
        [ScriptCode("ADDRANDOMMAPGATE")]
        ADDRANDOMMAPGATE,
        [ScriptCode("DELRANDOMMAPGATE")]
        DELRANDOMMAPGATE,
        [ScriptCode("GETRANDOMMAPGATE")]
        GETRANDOMMAPGATE,
        [ScriptCode("OPENBOOK")]
        OPENBOOK,
        [ScriptCode("OPENBOX")]
        OPENBOX,
        [ScriptCode("CHANGEITEMS")]
        CHANGEITEMS,
        [ScriptCode("CLEARREMEMBER")]
        CLEARREMEMBER,
        [ScriptCode("SENDMOVEMSG")]
        SENDMOVEMSG,
        [ScriptCode("RECALLHERO")]
        RECALLHERO,
        [ScriptCode("HEROLOGOUT")]
        HEROLOGOUT,
        [ScriptCode("SETITEMSLIGHT")]
        SETITEMSLIGHT,
        [ScriptCode("READRANDOMSTR")]
        READRANDOMSTR,
        [ScriptCode("CHANGERANGEMONPOS")]
        CHANGERANGEMONPOS,
        [ScriptCode("READ")]
        READ,
        [ScriptCode("WRITE")]
        WRITE,
        [ScriptCode("CHANGEITEMNEWADDVALUE")]
        CHANGEITEMNEWADDVALUE,
        [ScriptCode("OPENHOMEPAGE")]
        OPENHOMEPAGE,
        [ScriptCode("PKZONEX")]
        PKZONEX,
        [ScriptCode("SETITEMSLIGHTEX")]
        SETITEMSLIGHTEX,
        [ScriptCode("SPELL")]
        SPELL,
        [ScriptCode("ADDMAPMAGICEVENT")]
        ADDMAPMAGICEVENT,
        [ScriptCode("RANDOMADDMAPMAGICEVENT")]
        RANDOMADDMAPMAGICEVENT,
        [ScriptCode("SNOW")]
        SNOW,
        [ScriptCode("RANDOMUPGRADEITEM")]
        RANDOMUPGRADEITEM,
        [ScriptCode("LOCK")]
        LOCK,
        [ScriptCode("UNLOCK")]
        UNLOCK,
        [ScriptCode("CLEARDUELMAP")]
        CLEARDUELMAP,
        [ScriptCode("GETDUELITEMS")]
        GETDUELITEMS,
        [ScriptCode("APPDUEL")]
        APPDUEL,
        [ScriptCode("CANUSEITEM")]
        CANUSEITEM,
        [ScriptCode("AUTOGOTOXY")]
        AUTOGOTOXY,
        [ScriptCode("CHANGENEWSTATUS")]
        CHANGENEWSTATUS,
        [ScriptCode("SENDDELAYMSG")]
        SENDDELAYMSG,
        [ScriptCode("ACTVARLIST")]
        ACTVARLIST,
        [ScriptCode("SETMASKED")]
        SETMASKED,
        [ScriptCode("SENDCENTERMSG")]
        SENDCENTERMSG,
        [ScriptCode("CHANGEUSEITEMSTARSLEVEL")]
        CHANGEUSEITEMSTARSLEVEL,
        [ScriptCode("CHANGEBAGITEMSTARSLEVEL")]
        CHANGEBAGITEMSTARSLEVEL,
        [ScriptCode("BINDBAGITEM")]
        BINDBAGITEM,
        [ScriptCode("HEROGROUP")]
        HEROGROUP,
        [ScriptCode("UNHEROGROUP")]
        UNHEROGROUP,
        [ScriptCode("SETONTIMER")]
        SETSCTIMER,
        [ScriptCode("SETOFFTIMER")]
        KILLSCTIMER,
        [ScriptCode("PLAYSOUND")]
        PLAYSOUND,
        [ScriptCode("SHOWEFFECT")]
        SHOWEFFECT,
        [ScriptCode("CHANGEITEMVALUE")]
        CHANGEITEMVALUE,
        [ScriptCode("VIBRATION")]
        VIBRATION,
        [ScriptCode("OPENBIGDIALOGBOX")]
        OPENBIGDIALOGBOX,
        [ScriptCode("CLOSEBIGDIALOGBOX")]
        CLOSEBIGDIALOGBOX,
        [ScriptCode("TAGMAPMOVE")]
        TAGMAPMOVE,
        [ScriptCode("TAGMAPINFO")]
        TAGMAPINFO,
        [ScriptCode("AISTART")]
        AISTART,
        [ScriptCode("AISTOP")]
        AISTOP,
        [ScriptCode("CHANGEIPADDRESS")]
        CHANGEIPADDRESS,
        [ScriptCode("CHANGEATTATCKMODE")]
        CHANGEATTATCKMODE,
        [ScriptCode("AILOGON")]
        AILOGON,
        [ScriptCode("AILOGONEX")]
        AILOGONEX,
        [ScriptCode("KICKALL")]
        KICKALL,
        [ScriptCode("TAKEITEMLIST")]
        TAKEITEMLIST,
        [ScriptCode("SHOWRANKLEVLNAME")]
        SHOWRANKLEVLNAME,
        [ScriptCode("LOADROBOTCONFIG")]
        LOADROBOTCONFIG,
        [ScriptCode("ACTMISSION")]
        ACTMISSION,
        [ScriptCode("GUILDRECALL")]
        GUILDRECALL,
        [ScriptCode("GROUPADDLIST")]
        GROUPADDLIST,
        [ScriptCode("CLEARLIST")]
        CLEARLIST,
        [ScriptCode("GROUPRECALL")]
        GROUPRECALL,
        [ScriptCode("GROUPMOVEMAP")]
        GROUPMOVEMAP,
        [ScriptCode("SAVESLAVES")]
        SAVESLAVES,
        /// <summary>
        // 检查会员时间
        /// </summary>
        [ScriptCode("CHECKUSERDATE")]
        CHECKUSERDATE,
        /// <summary>
        /// 加入会员人物及时间
        /// </summary>
        [ScriptCode("ADDUSERDATE")]
        ADDUSERDATE,
        /// <summary>
        /// 删除会员人物及时间
        /// </summary>
        [ScriptCode("DELUSERDATE")]
        DELUSERDATE,
        /// <summary>
        /// 挂机
        /// </summary>
        [ScriptCode("OFFLINE")]
        OffLine,
        /// <summary>
        /// 特修身上所有装备
        /// </summary>
        [ScriptCode("REPAIRALL")]
        REPAIRALL,
        /// <summary>
        /// 产生一个随机数字
        /// </summary>
        [ScriptCode("SETRANDOMNO")]
        SETRANDOMNO,
        /// <summary>
        /// 刷新包裹物品命令
        /// </summary>
        [ScriptCode("QUERYBAGITEMS")]
        QUERYBAGITEMS,
        /// <summary>
        /// 将指定物品刷新到指定地图坐标范围内
        /// </summary>
        [ScriptCode("THROWITEM")]
        THROWITEM,
        /// <summary>
        /// 开通元宝交易
        /// </summary>
        [ScriptCode("OPENYBDEAL")]
        OPENYBDEAL,
        /// <summary>
        /// 查询可以的购买物品
        /// </summary>        
        [ScriptCode("QUERYYBSELL")]
        QUERYYBSELL,
        [ScriptCode("QUERYYBDEAL")]
        QUERYYBDEAL,
        /// <summary>
        /// 延时跳转
        /// </summary>
        [ScriptCode("DELAYGOTO")]
        DELAYGOTO,
        [ScriptCode("DELAYCALL")]
        DELAYCALL,
        /// <summary>
        /// 获取客户端输入值
        /// </summary>
        [ScriptCode("QUERYVALUE")]
        QUERYVALUE,
        /// <summary>
        /// 杀死所有宠物
        /// </summary>
        [ScriptCode("KILLSLAVENAME")]
        KILLSLAVENAME,
        /// <summary>
        /// 查询物品信息
        /// </summary>
        [ScriptCode("QUERYITEMDLG")]
        QUERYITEMDLG,
        /// <summary>
        /// 升级对话框中的物品
        /// </summary>
        [ScriptCode("UPGRADEDLGITEM")]
        UPGRADEDLGITEM,
        /// <summary>
        /// 获取装备指定属性到变量中
        /// </summary>
        [ScriptCode("GETDLGITEMVALUE")]
        GETDLGITEMVALUE,
        /// <summary>
        /// 回收对话框中的物品
        /// </summary>
        [ScriptCode("TAKEDLGITEM")]
        TakeDlgItem
    }
}